[package]
name = "ton-client-rs"
version = "0.21.0"
description = "TON SDK Client Library for Rust"
authors = ["TON DEV SOLUTIONS LTD <support@tonlabs.io>"]
edition = "2020"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://ton.dev"
repository = "https://github.com/tonlabs/ton-client-rs"
documentation = "https://docs.ton.dev"
keywords = ["TON", "blockchain", "cryptography", "network"]
build = "build.rs"

[dependencies]
hex = "0.3.2"
serde_json = "1.0.39"
serde_derive = "1.0.91"
serde = "1.0.91"
base64 = "0.10.0"
futures = "0.1.26"
crc16 = "0.4.0"
error-chain = { version = "^0.12", default-features = false }

[build-dependencies]
curl = "0.4.19"
flate2 = "1.0.4"
