[package]
name = "ton-client-rs"
version = "0.11.0"
authors = ["TON DEV SOLUTIONS LTD <support@tonlabs.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
hex = "0.3.2"
serde_json = "1.0.39"
serde_derive = "1.0.91"
serde = "1.0.91"
base64 = "0.10.0"

[build-dependencies]
curl = "0.4.19"
flate2 = "1.0.4"
